/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package minicad;

import java.awt.*;
import java.util.ArrayList;
import java.util.HashMap;

/**
 *
 * @author Mario Pineda
 */
public class PanelDibujable extends javax.swing.JPanel {

    private ArrayList<Polygon> formas = new ArrayList<Polygon>();
    private HashMap mapa = new HashMap();
    private double[][] matriz;
    private int[][] matrizIdentidad;

    /**
     * Creates new form PanelDibujable
     */
    public PanelDibujable() {
        initComponents();
        this.setBackground(Color.WHITE);
        //crearIdentidad();
    }

    public void setFigura() {

    }

//    public void crearIdentidad() {
//        matrizIdentidad[0][0] = 1;
//        matrizIdentidad[0][1] = 0;
//        matrizIdentidad[0][2] = 0;
//        matrizIdentidad[1][0] = 0;
//        matrizIdentidad[1][1] = 1;
//        matrizIdentidad[1][2] = 0;
//        matrizIdentidad[2][0] = 0;
//        matrizIdentidad[2][1] = 0;
//        matrizIdentidad[2][2] = 1;
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}

class Figura {

    private int puntos;

    public Figura(int puntos) {
        this.puntos = puntos;
    }
}
